// Package inspectcsv generates GORM models from sampled CSV data.
package inspectcsv

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"text/template"

	"go/format"

	"github.com/edcrewe/gormcsv/meta"
)

//go:embed models.tmpl
var modelsTemplate string

// GenerateFile uses csvmeta to generate models.go to the specified path
func GenerateFile(csvMeta meta.CSVMeta, path string) error {
	var generated bytes.Buffer
	if err := Generate(&generated, csvMeta); err != nil {
		return err
	}

	cleanPath := filepath.Clean(path)
	directory := filepath.Dir(cleanPath)
	temporary, err := os.CreateTemp(directory, ".gormcsv-models-*") // #nosec G304 -- path is explicitly supplied by the user
	if err != nil {
		return fmt.Errorf("create temporary model file: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if _, err := temporary.Write(generated.Bytes()); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("write temporary model file: %w", err)
	}
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return fmt.Errorf("set model file permissions: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary model file: %w", err)
	}
	if err := os.Rename(temporaryPath, cleanPath); err != nil {
		return fmt.Errorf("replace %q: %w", path, err)
	}
	return nil
}

// Generate uses csvmeta to generate each model to the provided writer
func Generate(w io.Writer, csvMeta meta.CSVMeta) error {
	t, err := template.New("models").Parse(modelsTemplate)
	if err != nil {
		return fmt.Errorf("parse models template: %w", err)
	}
	var generated bytes.Buffer
	if err := t.Execute(&generated, csvMeta); err != nil {
		return fmt.Errorf("execute models template: %w", err)
	}
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		return fmt.Errorf("format generated models: %w", err)
	}
	if _, err := w.Write(formatted); err != nil {
		return fmt.Errorf("write generated models: %w", err)
	}
	return nil
}
