// Generated by gormcsv.
package importcsv

import (
	"gorm.io/gorm"
)

// MakeModels returns the models available to the command.
func MakeModels() ModelFactory {
	return NewModelFactory(map[string]func() any{
		"country":   func() any { return &Country{} },
		"testtypes": func() any { return &TestTypes{} },
	})
}

type Country struct {
	gorm.Model
	Latitude  float64
	Have      int64
	That      int64
	Longitude float64
	In        int64
	Our       int64
	Name      string
	Code      string
	Other     int64
	Data      int64
	We        int64
	Dont      int64
	Alias     string
	Some      string
}

type TestTypes struct {
	gorm.Model
	Intcol     int16
	Boolcol    bool
	Datecol    string
	Wordcol    string
	Codecol    string
	Textcol    string
	Bigtextcol string
	Numbercol  float32
}
